// Auto-generated by generate_data_js.py — demo data (no CI run yet).
// Generated: 2026-05-27 10:44 UTC
const RUN_META = {
  "id": "run-42",
  "commit": "5764498",
  "branch": "main",
  "triggeredBy": "mejbaurbahar",
  "startedAt": "2026-05-27T06:42:11Z",
  "duration": 3284,
  "device": "Pixel 7 \u00b7 Android 14 \u00b7 API 34",
  "flutterVersion": "3.27.1",
  "neverRan": false,
  "isMockData": false
};
const MAESTRO_FLOWS = [
  {
    "id": 1,
    "name": "Splash / Onboarding",
    "group": "Onboarding",
    "coverage": "Country + language selection",
    "duration": 38,
    "steps": 14,
    "status": "pass",
    "screens": 6
  },
  {
    "id": 2,
    "name": "Login OTP",
    "group": "Auth",
    "coverage": "Phone \u2192 OTP \u2192 logged in",
    "duration": 52,
    "steps": 19,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 3,
    "name": "Guest User",
    "group": "Auth",
    "coverage": "Guest browsing + login gate",
    "duration": 41,
    "steps": 12,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 4,
    "name": "Browse Services",
    "group": "Catalog",
    "coverage": "Mosque listing + selection",
    "duration": 67,
    "steps": 22,
    "status": "pass",
    "screens": 8
  },
  {
    "id": 5,
    "name": "Cart",
    "group": "Commerce",
    "coverage": "Add items, quantity, price, tax",
    "duration": 71,
    "steps": 24,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 6,
    "name": "Checkout",
    "group": "Commerce",
    "coverage": "Payment method + promo code",
    "duration": 89,
    "steps": 31,
    "status": "pass",
    "screens": 7
  },
  {
    "id": 7,
    "name": "Gift Card",
    "group": "Commerce",
    "coverage": "Full send flow + WhatsApp preview",
    "duration": 96,
    "steps": 27,
    "status": "flaky",
    "screens": 9,
    "note": "Gift card WhatsApp preview timed out \u2014 passed on retry"
  },
  {
    "id": 8,
    "name": "My Orders",
    "group": "Account",
    "coverage": "List, detail, rating",
    "duration": 58,
    "steps": 18,
    "status": "pass",
    "screens": 6
  },
  {
    "id": 9,
    "name": "Subscription",
    "group": "Commerce",
    "coverage": "Weekly / monthly recurring",
    "duration": 102,
    "steps": 29,
    "status": "pass",
    "screens": 8
  },
  {
    "id": 10,
    "name": "Multi-language",
    "group": "i18n",
    "coverage": "Arabic, Turkish, Urdu, English",
    "duration": 124,
    "steps": 36,
    "status": "pass",
    "screens": 12
  },
  {
    "id": 11,
    "name": "No Internet",
    "group": "Resilience",
    "coverage": "Offline error screen",
    "duration": 22,
    "steps": 7,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 12,
    "name": "Profile & Settings",
    "group": "Account",
    "coverage": "Currency, About, Logout dialog",
    "duration": 74,
    "steps": 26,
    "status": "pass",
    "screens": 7
  },
  {
    "id": 13,
    "name": "Help & Support",
    "group": "Account",
    "coverage": "Help centre, WhatsApp, email",
    "duration": 49,
    "steps": 16,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 14,
    "name": "Manage Subscriptions",
    "group": "Account",
    "coverage": "Active list, billing history, cancel",
    "duration": 81,
    "steps": 23,
    "status": "pass",
    "screens": 6
  },
  {
    "id": 15,
    "name": "Cancel Order",
    "group": "Commerce",
    "coverage": "Cancel dialog, confirm/decline",
    "duration": 44,
    "steps": 14,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 16,
    "name": "Share App",
    "group": "Growth",
    "coverage": "Referral link sharing",
    "duration": 31,
    "steps": 9,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 17,
    "name": "Login Invalid Phone",
    "group": "Auth",
    "coverage": "Non-existent / malformed phone",
    "duration": 24,
    "steps": 8,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 18,
    "name": "Login Wrong OTP",
    "group": "Auth",
    "coverage": "Wrong OTP, retry, lockout",
    "duration": 31,
    "steps": 10,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 19,
    "name": "Invalid Promo",
    "group": "Commerce",
    "coverage": "Expired / non-existent promo code",
    "duration": 28,
    "steps": 9,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 20,
    "name": "Empty Cart Checkout",
    "group": "Commerce",
    "coverage": "Checkout blocked with empty cart",
    "duration": 18,
    "steps": 6,
    "status": "pass",
    "screens": 1
  },
  {
    "id": 21,
    "name": "Gift Card Validation",
    "group": "Commerce",
    "coverage": "Missing fields, invalid email",
    "duration": 33,
    "steps": 11,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 22,
    "name": "Cart Qty Boundary",
    "group": "Commerce",
    "coverage": "Max/min quantity, +/- at boundary",
    "duration": 41,
    "steps": 13,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 23,
    "name": "App Background Resume",
    "group": "Resilience",
    "coverage": "Background 10s, foreground, state intact",
    "duration": 29,
    "steps": 10,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 24,
    "name": "Browse Search Edges",
    "group": "Catalog",
    "coverage": "Empty, Arabic, XSS, SQL, gibberish",
    "duration": 58,
    "steps": 21,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 25,
    "name": "Payment Input Edges",
    "group": "Commerce",
    "coverage": "Spaces, CAPS, far-future expiry, zeros",
    "duration": 54,
    "steps": 20,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 26,
    "name": "Home Feed",
    "group": "UX",
    "coverage": "Carousel, banner taps, featured providers",
    "duration": 58,
    "steps": 18,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 27,
    "name": "Booking Flow",
    "group": "Booking",
    "coverage": "Select provider, date, slot \u2192 confirm",
    "duration": 92,
    "steps": 31,
    "status": "pass",
    "screens": 8
  },
  {
    "id": 28,
    "name": "Booking Reschedule",
    "group": "Booking",
    "coverage": "Change date and time of existing booking",
    "duration": 64,
    "steps": 22,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 29,
    "name": "Booking Cancel",
    "group": "Booking",
    "coverage": "Cancel booking, confirm dialog",
    "duration": 52,
    "steps": 18,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 30,
    "name": "Notifications",
    "group": "Account",
    "coverage": "Notification list, mark-read, deep link",
    "duration": 42,
    "steps": 14,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 31,
    "name": "Wallet Balance",
    "group": "Commerce",
    "coverage": "Balance display, top-up CTA, history",
    "duration": 48,
    "steps": 16,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 32,
    "name": "Ratings & Reviews",
    "group": "Account",
    "coverage": "Post booking rating, comment, star picker",
    "duration": 56,
    "steps": 19,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 33,
    "name": "Map Location",
    "group": "UX",
    "coverage": "Salon map pins, detail sheet, directions",
    "duration": 72,
    "steps": 23,
    "status": "pass",
    "screens": 6
  },
  {
    "id": 34,
    "name": "Favourites",
    "group": "Account",
    "coverage": "Add/remove favourite, list persistence",
    "duration": 44,
    "steps": 15,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 35,
    "name": "Refer a Friend",
    "group": "Growth",
    "coverage": "Referral link share sheet, copy link",
    "duration": 28,
    "steps": 9,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 36,
    "name": "Dark Mode",
    "group": "UX",
    "coverage": "Toggle, colour-scheme preserves state",
    "duration": 24,
    "steps": 8,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 37,
    "name": "Accessibility Labels",
    "group": "A11y",
    "coverage": "Content descriptions, focus order",
    "duration": 42,
    "steps": 14,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 38,
    "name": "Session Timeout",
    "group": "Auth",
    "coverage": "Idle 30 min, auto-logout, re-login prompt",
    "duration": 36,
    "steps": 12,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 39,
    "name": "Deep Link / QR",
    "group": "Growth",
    "coverage": "Open via QR, deep-link to booking screen",
    "duration": 32,
    "steps": 10,
    "status": "flaky",
    "screens": 3,
    "note": "QR scan deep-link navigation took >5s on first attempt \u2014 passed on retry"
  },
  {
    "id": 40,
    "name": "App Update Prompt",
    "group": "Resilience",
    "coverage": "In-app update dialog, dismiss, force",
    "duration": 26,
    "steps": 8,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 41,
    "name": "Salon Profile View",
    "group": "UX",
    "coverage": "Salon details, gallery, reviews, book-now",
    "duration": 62,
    "steps": 20,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 42,
    "name": "Search with Filters",
    "group": "Browse",
    "coverage": "Category, price, sort filters, clear",
    "duration": 56,
    "steps": 18,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 43,
    "name": "Payment Methods",
    "group": "Commerce",
    "coverage": "Add card, saved cards list, delete card",
    "duration": 66,
    "steps": 22,
    "status": "pass",
    "screens": 5
  },
  {
    "id": 44,
    "name": "Wallet Top-up",
    "group": "Commerce",
    "coverage": "Add balance, payment confirm, history",
    "duration": 50,
    "steps": 16,
    "status": "pass",
    "screens": 4
  },
  {
    "id": 45,
    "name": "Logout Success",
    "group": "Auth",
    "coverage": "Confirm logout, return to login screen",
    "duration": 30,
    "steps": 10,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 46,
    "name": "Edit Profile",
    "group": "Account",
    "coverage": "Update name, avatar, save changes",
    "duration": 42,
    "steps": 14,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 47,
    "name": "OTP Resend",
    "group": "Auth",
    "coverage": "Resend code, wait, enter new OTP",
    "duration": 36,
    "steps": 12,
    "status": "flaky",
    "screens": 3,
    "note": "OTP resend endpoint returned 429 on first attempt \u2014 passed on retry"
  },
  {
    "id": 48,
    "name": "Location Permission",
    "group": "UX",
    "coverage": "Allow location, map loads, tap pin",
    "duration": 46,
    "steps": 15,
    "status": "pass",
    "screens": 3
  },
  {
    "id": 49,
    "name": "App Permissions",
    "group": "Account",
    "coverage": "Notifications toggle, location enable",
    "duration": 34,
    "steps": 11,
    "status": "pass",
    "screens": 2
  },
  {
    "id": 50,
    "name": "Language Switch",
    "group": "UX",
    "coverage": "Switch to Arabic, RTL layout, back to EN",
    "duration": 48,
    "steps": 16,
    "status": "pass",
    "screens": 4
  }
];
const APPIUM_TESTS = [
  {
    "file": "test_card_payment.py",
    "group": "Payment",
    "icon": "card",
    "tests": [
      {
        "name": "test_hyperpay_card_success",
        "duration": 14.2,
        "status": "pass"
      },
      {
        "name": "test_expired_card_rejected",
        "duration": 9.8,
        "status": "pass"
      },
      {
        "name": "test_declined_card_message",
        "duration": 11.4,
        "status": "pass"
      },
      {
        "name": "test_promo_code_applied",
        "duration": 7.6,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_tabby_bnpl.py",
    "group": "Payment",
    "icon": "split",
    "tests": [
      {
        "name": "test_tabby_visibility",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_shariah_badge_shown",
        "duration": 4.7,
        "status": "pass"
      },
      {
        "name": "test_learn_more_modal",
        "duration": 6.2,
        "status": "pass"
      },
      {
        "name": "test_cancel_flow",
        "duration": 8.4,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_bank_transfer.py",
    "group": "Payment",
    "icon": "bank",
    "tests": [
      {
        "name": "test_account_details_visible",
        "duration": 4.3,
        "status": "pass"
      },
      {
        "name": "test_receipt_upload_prompt",
        "duration": 7.9,
        "status": "pass"
      },
      {
        "name": "test_photo_gallery_options",
        "duration": 5.5,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_gift_card.py",
    "group": "Commerce",
    "icon": "gift",
    "tests": [
      {
        "name": "test_field_validation",
        "duration": 12.6,
        "status": "pass"
      },
      {
        "name": "test_preview_accuracy",
        "duration": 9.1,
        "status": "pass"
      },
      {
        "name": "test_gifts_received_section",
        "duration": 6.8,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_subscription.py",
    "group": "Commerce",
    "icon": "repeat",
    "tests": [
      {
        "name": "test_weekly_cadence",
        "duration": 15.4,
        "status": "pass"
      },
      {
        "name": "test_monthly_cadence",
        "duration": 14.8,
        "status": "pass"
      },
      {
        "name": "test_skip_week",
        "duration": 8.2,
        "status": "pass"
      },
      {
        "name": "test_success_banner",
        "duration": 5.6,
        "status": "pass"
      },
      {
        "name": "test_unavailable_items",
        "duration": 9.7,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_live_broadcast.py",
    "group": "Live",
    "icon": "video",
    "tests": [
      {
        "name": "test_broadcast_screen_loads",
        "duration": 11.2,
        "status": "pass"
      },
      {
        "name": "test_visual_docs_render",
        "duration": 8.5,
        "status": "pass"
      },
      {
        "name": "test_permission_handling",
        "duration": 13.8,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_profile.py",
    "group": "Account",
    "icon": "user",
    "tests": [
      {
        "name": "test_currency_switch",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_about_page",
        "duration": 4.4,
        "status": "pass"
      },
      {
        "name": "test_logout_dialog",
        "duration": 5.8,
        "status": "pass"
      },
      {
        "name": "test_delete_account",
        "duration": 9.3,
        "status": "pass"
      },
      {
        "name": "test_billing_history",
        "duration": 6.9,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_payment_negative.py",
    "group": "Payment",
    "icon": "shield",
    "tests": [
      {
        "name": "test_short_card_number_shows_error",
        "duration": 8.2,
        "status": "pass"
      },
      {
        "name": "test_letters_in_card_number_shows_error",
        "duration": 7.6,
        "status": "pass"
      },
      {
        "name": "test_invalid_expiry_month_shows_error",
        "duration": 8.1,
        "status": "pass"
      },
      {
        "name": "test_past_year_expiry_shows_error",
        "duration": 7.8,
        "status": "pass"
      },
      {
        "name": "test_empty_cvv_shows_error",
        "duration": 7.3,
        "status": "pass"
      },
      {
        "name": "test_single_digit_cvv_shows_error",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_empty_cardholder_name_shows_error",
        "duration": 7.4,
        "status": "pass"
      },
      {
        "name": "test_all_zeros_card_shows_error",
        "duration": 8.5,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_payment_extended.py",
    "group": "Payment",
    "icon": "card",
    "tests": [
      {
        "name": "test_card_number_with_spaces",
        "duration": 6.2,
        "status": "pass"
      },
      {
        "name": "test_card_number_with_dashes",
        "duration": 5.8,
        "status": "pass"
      },
      {
        "name": "test_card_number_with_padding_spaces",
        "duration": 5.4,
        "status": "pass"
      },
      {
        "name": "test_card_number_max_16_digits",
        "duration": 4.9,
        "status": "pass"
      },
      {
        "name": "test_cvv_letters_rejected",
        "duration": 4.2,
        "status": "pass"
      },
      {
        "name": "test_cvv_special_chars_rejected",
        "duration": 4.1,
        "status": "pass"
      },
      {
        "name": "test_cvv_4_digit_amex",
        "duration": 5.3,
        "status": "pass"
      },
      {
        "name": "test_expiry_current_month_valid",
        "duration": 5.7,
        "status": "pass"
      },
      {
        "name": "test_expiry_far_future_accepted",
        "duration": 4.8,
        "status": "pass"
      },
      {
        "name": "test_expiry_no_slash_format",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_expiry_month_00_rejected",
        "duration": 4.6,
        "status": "pass"
      },
      {
        "name": "test_cardholder_numbers_rejected",
        "duration": 5.0,
        "status": "pass"
      },
      {
        "name": "test_cardholder_all_spaces_rejected",
        "duration": 4.3,
        "status": "pass"
      },
      {
        "name": "test_cardholder_uppercase_accepted",
        "duration": 4.7,
        "status": "pass"
      },
      {
        "name": "test_cardholder_50_chars",
        "duration": 5.5,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_login_negative.py",
    "group": "Auth",
    "icon": "lock",
    "tests": [
      {
        "name": "test_empty_phone_blocks_continue",
        "duration": 4.8,
        "status": "pass"
      },
      {
        "name": "test_too_short_phone_shows_error",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_too_long_phone_shows_error",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_letters_in_phone_shows_error",
        "duration": 5.3,
        "status": "pass"
      },
      {
        "name": "test_special_chars_in_phone_shows_error",
        "duration": 5.4,
        "status": "pass"
      },
      {
        "name": "test_wrong_otp_shows_error",
        "duration": 8.7,
        "status": "flaky",
        "error": "StaleElementReferenceException: element detached after OTP screen transition \u2014 passed on retry"
      },
      {
        "name": "test_all_zeros_otp_shows_error",
        "duration": 8.4,
        "status": "pass"
      },
      {
        "name": "test_empty_otp_blocks_verify",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_otp_resend_link_visible",
        "duration": 6.8,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_auth_edge_cases.py",
    "group": "Auth",
    "icon": "lock",
    "tests": [
      {
        "name": "test_phone_leading_spaces_stripped",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_phone_plus880_prefix",
        "duration": 4.8,
        "status": "pass"
      },
      {
        "name": "test_phone_all_same_digits",
        "duration": 4.5,
        "status": "pass"
      },
      {
        "name": "test_phone_starts_with_zero",
        "duration": 4.3,
        "status": "pass"
      },
      {
        "name": "test_phone_with_dots",
        "duration": 4.1,
        "status": "pass"
      },
      {
        "name": "test_phone_with_parentheses",
        "duration": 4.2,
        "status": "pass"
      },
      {
        "name": "test_phone_max_length",
        "duration": 4.7,
        "status": "pass"
      },
      {
        "name": "test_phone_uppercase_blocked",
        "duration": 4.0,
        "status": "pass"
      },
      {
        "name": "test_phone_emoji_blocked",
        "duration": 4.4,
        "status": "pass"
      },
      {
        "name": "test_otp_spaces_between_digits",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_otp_uppercase_blocked",
        "duration": 4.2,
        "status": "pass"
      },
      {
        "name": "test_otp_special_chars_blocked",
        "duration": 4.3,
        "status": "pass"
      },
      {
        "name": "test_otp_100_digit_input",
        "duration": 4.6,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_cart_boundary.py",
    "group": "Commerce",
    "icon": "bag",
    "tests": [
      {
        "name": "test_empty_cart_checkout_is_blocked",
        "duration": 6.3,
        "status": "pass"
      },
      {
        "name": "test_quantity_increment_updates_total",
        "duration": 8.7,
        "status": "pass"
      },
      {
        "name": "test_quantity_decrement_to_one_keeps_item",
        "duration": 9.1,
        "status": "pass"
      },
      {
        "name": "test_quantity_decrement_at_one_removes_or_prompts",
        "duration": 8.4,
        "status": "pass"
      },
      {
        "name": "test_maximum_quantity_does_not_crash",
        "duration": 14.2,
        "status": "flaky",
        "error": "StaleElementReferenceException: '+' button re-bound after scroll \u2014 passed on retry"
      },
      {
        "name": "test_remove_all_items_shows_empty_state",
        "duration": 7.8,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_promo_codes.py",
    "group": "Commerce",
    "icon": "tag",
    "tests": [
      {
        "name": "test_valid_promo_applies_successfully",
        "duration": 9.4,
        "status": "pass"
      },
      {
        "name": "test_invalid_promo_shows_error",
        "duration": 8.1,
        "status": "pass"
      },
      {
        "name": "test_empty_promo_shows_error",
        "duration": 5.6,
        "status": "pass"
      },
      {
        "name": "test_expired_promo_shows_error",
        "duration": 8.3,
        "status": "pass"
      },
      {
        "name": "test_lowercase_promo_handled",
        "duration": 8.7,
        "status": "pass"
      },
      {
        "name": "test_promo_with_spaces_is_trimmed_or_rejected",
        "duration": 8.5,
        "status": "pass"
      },
      {
        "name": "test_special_chars_promo_shows_error",
        "duration": 7.4,
        "status": "pass"
      },
      {
        "name": "test_sql_injection_in_promo_is_safe",
        "duration": 8.9,
        "status": "pass"
      },
      {
        "name": "test_very_long_promo_does_not_crash",
        "duration": 7.6,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_gift_card_boundary.py",
    "group": "Commerce",
    "icon": "gift",
    "tests": [
      {
        "name": "test_very_long_recipient_name_handled",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_special_chars_in_recipient_name",
        "duration": 6.2,
        "status": "pass"
      },
      {
        "name": "test_arabic_name_accepted",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_invalid_recipient_phone_shows_error",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_short_recipient_phone_shows_error",
        "duration": 6.7,
        "status": "pass"
      },
      {
        "name": "test_xss_in_message_is_safe",
        "duration": 7.4,
        "status": "pass"
      },
      {
        "name": "test_sql_injection_in_message_is_safe",
        "duration": 7.8,
        "status": "pass"
      },
      {
        "name": "test_emoji_in_message_does_not_crash",
        "duration": 6.4,
        "status": "pass"
      },
      {
        "name": "test_very_long_message_is_handled",
        "duration": 6.9,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_subscription_boundary.py",
    "group": "Commerce",
    "icon": "repeat",
    "tests": [
      {
        "name": "test_skipping_subscription_reaches_payment",
        "duration": 9.1,
        "status": "pass"
      },
      {
        "name": "test_weekly_then_back_resets_selection",
        "duration": 8.6,
        "status": "pass"
      },
      {
        "name": "test_subscription_prompt_has_both_options",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_subscription_frequency_options_shown",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_cancel_active_subscription_declined",
        "duration": 11.3,
        "status": "flaky",
        "error": "TimeoutException: 'No' button took >8s to appear \u2014 passed on retry"
      },
      {
        "name": "test_billing_history_accessible",
        "duration": 9.7,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_profile_edge_cases.py",
    "group": "Account",
    "icon": "user",
    "tests": [
      {
        "name": "test_logout_cancel_stays_logged_in",
        "duration": 7.2,
        "status": "pass"
      },
      {
        "name": "test_delete_account_cancel_stays_active",
        "duration": 7.8,
        "status": "pass"
      },
      {
        "name": "test_currency_list_loads_without_error",
        "duration": 6.4,
        "status": "pass"
      },
      {
        "name": "test_about_page_has_app_info",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_help_support_contact_options_visible",
        "duration": 8.1,
        "status": "pass"
      },
      {
        "name": "test_help_search_no_results_shows_empty_state",
        "duration": 7.6,
        "status": "pass"
      },
      {
        "name": "test_help_search_sql_injection_is_safe",
        "duration": 8.2,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_orders_edge_cases.py",
    "group": "Account",
    "icon": "list",
    "tests": [
      {
        "name": "test_search_with_no_results_shows_empty_state",
        "duration": 7.3,
        "status": "pass"
      },
      {
        "name": "test_search_with_special_chars_does_not_crash",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_empty_rating_feedback_shows_error",
        "duration": 9.1,
        "status": "pass"
      },
      {
        "name": "test_long_rating_feedback_is_handled",
        "duration": 10.4,
        "status": "pass"
      },
      {
        "name": "test_special_chars_in_feedback_are_safe",
        "duration": 9.7,
        "status": "pass"
      },
      {
        "name": "test_order_detail_shows_required_fields",
        "duration": 7.6,
        "status": "pass"
      },
      {
        "name": "test_cancel_order_dialog_can_be_dismissed",
        "duration": 8.2,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_browse_search.py",
    "group": "Catalog",
    "icon": "search",
    "tests": [
      {
        "name": "test_single_character_search",
        "duration": 4.8,
        "status": "pass"
      },
      {
        "name": "test_search_100_chars_does_not_crash",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_search_arabic_text",
        "duration": 5.4,
        "status": "pass"
      },
      {
        "name": "test_search_emoji_does_not_crash",
        "duration": 4.6,
        "status": "pass"
      },
      {
        "name": "test_search_all_uppercase_query",
        "duration": 4.7,
        "status": "pass"
      },
      {
        "name": "test_search_mixed_case",
        "duration": 4.5,
        "status": "pass"
      },
      {
        "name": "test_search_with_numbers_only",
        "duration": 4.3,
        "status": "pass"
      },
      {
        "name": "test_search_with_html_tags_is_safe",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_search_sql_injection_is_safe",
        "duration": 5.6,
        "status": "pass"
      },
      {
        "name": "test_search_gibberish_shows_empty_state",
        "duration": 5.8,
        "status": "pass"
      },
      {
        "name": "test_clear_search_restores_full_list",
        "duration": 4.9,
        "status": "pass"
      },
      {
        "name": "test_services_list_loads_without_login",
        "duration": 4.4,
        "status": "pass"
      },
      {
        "name": "test_service_card_tap_opens_detail",
        "duration": 5.3,
        "status": "pass"
      },
      {
        "name": "test_rapid_back_forth_navigation_no_crash",
        "duration": 6.1,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_checkout_edge_cases.py",
    "group": "Commerce",
    "icon": "bag",
    "tests": [
      {
        "name": "test_back_from_checkout_returns_to_cart",
        "duration": 7.2,
        "status": "pass"
      },
      {
        "name": "test_back_then_forward_preserves_cart",
        "duration": 8.1,
        "status": "pass"
      },
      {
        "name": "test_checkout_page_shows_order_summary",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_checkout_price_not_nan_or_zero",
        "duration": 6.3,
        "status": "pass"
      },
      {
        "name": "test_switch_from_card_to_tabby",
        "duration": 7.5,
        "status": "pass"
      },
      {
        "name": "test_switch_payment_method_multiple_times",
        "duration": 9.2,
        "status": "pass"
      },
      {
        "name": "test_coupon_applied_then_payment_selected",
        "duration": 8.7,
        "status": "pass"
      },
      {
        "name": "test_invalid_coupon_then_payment_selected",
        "duration": 7.4,
        "status": "pass"
      },
      {
        "name": "test_price_shows_currency_symbol",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_price_decimal_places_correct",
        "duration": 6.4,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_logout.py",
    "group": "Auth",
    "icon": "lock",
    "tests": [
      {
        "name": "test_logout_confirmation_dialog_shown",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_logout_cancel_keeps_session",
        "duration": 4.8,
        "status": "pass"
      },
      {
        "name": "test_logout_confirm_clears_session",
        "duration": 6.1,
        "status": "pass"
      },
      {
        "name": "test_logout_redirects_to_login",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_logout_clears_cart",
        "duration": 7.3,
        "status": "pass"
      },
      {
        "name": "test_logout_clears_favourites",
        "duration": 6.7,
        "status": "pass"
      },
      {
        "name": "test_relogin_after_logout_succeeds",
        "duration": 8.4,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_edit_profile.py",
    "group": "Account",
    "icon": "user",
    "tests": [
      {
        "name": "test_edit_profile_screen_loads",
        "duration": 4.6,
        "status": "pass"
      },
      {
        "name": "test_update_name_success",
        "duration": 6.2,
        "status": "pass"
      },
      {
        "name": "test_name_empty_shows_error",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_name_special_chars_handled",
        "duration": 5.4,
        "status": "pass"
      },
      {
        "name": "test_avatar_change_opens_picker",
        "duration": 7.8,
        "status": "pass"
      },
      {
        "name": "test_save_changes_shows_confirmation",
        "duration": 6.5,
        "status": "pass"
      },
      {
        "name": "test_back_without_save_prompts_discard",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_profile_changes_persist_after_reopen",
        "duration": 8.1,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_salon_profile.py",
    "group": "Catalog",
    "icon": "search",
    "tests": [
      {
        "name": "test_salon_profile_screen_loads",
        "duration": 5.3,
        "status": "pass"
      },
      {
        "name": "test_gallery_scroll_works",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_reviews_tab_loads",
        "duration": 5.7,
        "status": "pass"
      },
      {
        "name": "test_book_now_navigates_to_booking",
        "duration": 7.2,
        "status": "pass"
      },
      {
        "name": "test_salon_address_visible",
        "duration": 4.9,
        "status": "pass"
      },
      {
        "name": "test_salon_rating_displayed",
        "duration": 4.6,
        "status": "pass"
      },
      {
        "name": "test_gallery_image_full_screen",
        "duration": 6.1,
        "status": "pass"
      },
      {
        "name": "test_back_from_profile_returns_to_list",
        "duration": 5.4,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_search_filters.py",
    "group": "Browse",
    "icon": "search",
    "tests": [
      {
        "name": "test_filter_by_category_returns_results",
        "duration": 6.4,
        "status": "pass"
      },
      {
        "name": "test_filter_by_price_range_works",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_sort_by_rating_reorders_list",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_sort_by_price_reorders_list",
        "duration": 6.5,
        "status": "pass"
      },
      {
        "name": "test_clear_filters_restores_all",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_multiple_filters_combined",
        "duration": 8.3,
        "status": "pass"
      },
      {
        "name": "test_filter_no_results_shows_empty_state",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_filter_persists_across_navigation",
        "duration": 7.4,
        "status": "pass"
      },
      {
        "name": "test_filter_panel_opens_and_closes",
        "duration": 4.8,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_payment_methods.py",
    "group": "Commerce",
    "icon": "card",
    "tests": [
      {
        "name": "test_payment_methods_list_loads",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_add_new_card_form_shown",
        "duration": 6.3,
        "status": "pass"
      },
      {
        "name": "test_card_number_validation",
        "duration": 7.2,
        "status": "pass"
      },
      {
        "name": "test_expiry_validation",
        "duration": 6.8,
        "status": "pass"
      },
      {
        "name": "test_cvv_validation",
        "duration": 6.5,
        "status": "pass"
      },
      {
        "name": "test_card_saved_successfully",
        "duration": 8.4,
        "status": "pass"
      },
      {
        "name": "test_saved_card_shown_in_list",
        "duration": 5.9,
        "status": "pass"
      },
      {
        "name": "test_delete_card_confirmation_dialog",
        "duration": 6.7,
        "status": "pass"
      },
      {
        "name": "test_card_deleted_removed_from_list",
        "duration": 7.1,
        "status": "pass"
      },
      {
        "name": "test_default_card_indicator_shown",
        "duration": 5.4,
        "status": "pass"
      }
    ]
  },
  {
    "file": "test_wallet_topup.py",
    "group": "Commerce",
    "icon": "split",
    "tests": [
      {
        "name": "test_wallet_screen_shows_balance",
        "duration": 5.2,
        "status": "pass"
      },
      {
        "name": "test_topup_amount_entry",
        "duration": 6.1,
        "status": "pass"
      },
      {
        "name": "test_topup_zero_amount_blocked",
        "duration": 5.4,
        "status": "pass"
      },
      {
        "name": "test_topup_negative_amount_blocked",
        "duration": 5.1,
        "status": "pass"
      },
      {
        "name": "test_topup_payment_confirmation_shown",
        "duration": 7.8,
        "status": "pass"
      },
      {
        "name": "test_topup_success_updates_balance",
        "duration": 9.2,
        "status": "pass"
      },
      {
        "name": "test_topup_history_entry_added",
        "duration": 8.6,
        "status": "pass"
      },
      {
        "name": "test_topup_cancel_keeps_old_balance",
        "duration": 6.3,
        "status": "pass"
      },
      {
        "name": "test_wallet_history_loads",
        "duration": 5.7,
        "status": "pass"
      }
    ]
  }
];
const CI_WORKFLOWS = [
  {
    "name": "Maestro Smoke",
    "trigger": "Every push / PR",
    "duration": "~10 min",
    "coverage": "Login, booking, home feed",
    "status": "pass",
    "lastRun": "1h ago",
    "runs": 42,
    "passRate": 97.6
  },
  {
    "name": "Maestro Regression",
    "trigger": "Nightly 01:00 UTC",
    "duration": "~35 min",
    "coverage": "All 50 flows",
    "status": "pass",
    "lastRun": "7h ago",
    "runs": 18,
    "passRate": 95.0
  },
  {
    "name": "Appium Deep Tests",
    "trigger": "Every Monday",
    "duration": "~60 min",
    "coverage": "Booking, payment, wallet, account",
    "status": "pass",
    "lastRun": "2 days ago",
    "runs": 8,
    "passRate": 96.2
  },
  {
    "name": "Maestro iOS",
    "trigger": "Manual only",
    "duration": "~20 min",
    "coverage": "Smoke on iOS Simulator",
    "status": "idle",
    "lastRun": "never",
    "runs": 0,
    "passRate": 0
  },
  {
    "name": "Publish Report",
    "trigger": "After any test run",
    "duration": "~3 min",
    "coverage": "Deploys to GitHub Pages",
    "status": "pass",
    "lastRun": "1h ago",
    "runs": 62,
    "passRate": 100
  }
];
const HISTORY = [
  {
    "day": 29,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 3185
  },
  {
    "day": 28,
    "total": 50,
    "pass": 49,
    "fail": 1,
    "flaky": 0,
    "duration": 3106
  },
  {
    "day": 27,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 2581
  },
  {
    "day": 26,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2468
  },
  {
    "day": 25,
    "total": 50,
    "pass": 48,
    "fail": 1,
    "flaky": 1,
    "duration": 2565
  },
  {
    "day": 24,
    "total": 50,
    "pass": 49,
    "fail": 1,
    "flaky": 0,
    "duration": 2883
  },
  {
    "day": 23,
    "total": 50,
    "pass": 49,
    "fail": 0,
    "flaky": 1,
    "duration": 2652
  },
  {
    "day": 22,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2610
  },
  {
    "day": 21,
    "total": 50,
    "pass": 49,
    "fail": 1,
    "flaky": 0,
    "duration": 2891
  },
  {
    "day": 20,
    "total": 50,
    "pass": 49,
    "fail": 1,
    "flaky": 0,
    "duration": 3216
  },
  {
    "day": 19,
    "total": 50,
    "pass": 48,
    "fail": 1,
    "flaky": 1,
    "duration": 2536
  },
  {
    "day": 18,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 3050
  },
  {
    "day": 17,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 3120
  },
  {
    "day": 16,
    "total": 50,
    "pass": 49,
    "fail": 0,
    "flaky": 1,
    "duration": 2839
  },
  {
    "day": 15,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2658
  },
  {
    "day": 14,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2634
  },
  {
    "day": 13,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 2901
  },
  {
    "day": 12,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2573
  },
  {
    "day": 11,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 3140
  },
  {
    "day": 10,
    "total": 50,
    "pass": 49,
    "fail": 0,
    "flaky": 1,
    "duration": 3204
  },
  {
    "day": 9,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2742
  },
  {
    "day": 8,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 3053
  },
  {
    "day": 7,
    "total": 50,
    "pass": 48,
    "fail": 1,
    "flaky": 1,
    "duration": 2982
  },
  {
    "day": 6,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2840
  },
  {
    "day": 5,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2803
  },
  {
    "day": 4,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2498
  },
  {
    "day": 3,
    "total": 50,
    "pass": 47,
    "fail": 2,
    "flaky": 1,
    "duration": 2626
  },
  {
    "day": 2,
    "total": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "duration": 2648
  },
  {
    "day": 1,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2662
  },
  {
    "day": 0,
    "total": 50,
    "pass": 48,
    "fail": 2,
    "flaky": 0,
    "duration": 2626
  }
];
const COMMITS = [
  {
    "sha": "5764498",
    "msg": "Fix Bangladesh login automation",
    "author": "mejbaurbahar",
    "time": "1h ago",
    "tests": 50,
    "pass": 49,
    "fail": 0,
    "flaky": 1,
    "hasData": true
  },
  {
    "sha": "ba3f2ab",
    "msg": "Fix Bangladesh login country code selection",
    "author": "mejbaurbahar",
    "time": "3h ago",
    "tests": 50,
    "pass": 50,
    "fail": 0,
    "flaky": 0,
    "hasData": true
  },
  {
    "sha": "9d524ad",
    "msg": "feat(maestro): select Bangladesh country code in all flows",
    "author": "mejbaurbahar",
    "time": "8h ago",
    "tests": 50,
    "pass": 49,
    "fail": 0,
    "flaky": 1,
    "hasData": true
  },
  {
    "sha": "3617b04",
    "msg": "fix(runner): pre-flight checks, port-forward, per-flow error capture",
    "author": "mejbaurbahar",
    "time": "yesterday",
    "tests": 50,
    "pass": 48,
    "fail": 1,
    "flaky": 1,
    "hasData": true
  },
  {
    "sha": "a972d48",
    "msg": "fix(ci): add avd-name Pixel_7_API_34 + force-avd-creation",
    "author": "mejbaurbahar",
    "time": "2 days ago",
    "tests": 48,
    "pass": 47,
    "fail": 1,
    "flaky": 0,
    "hasData": true
  },
  {
    "sha": "c0ef551",
    "msg": "feat(booking): add reschedule and cancel flows",
    "author": "mejbaurbahar",
    "time": "3 days ago",
    "tests": 46,
    "pass": 46,
    "fail": 0,
    "flaky": 0,
    "hasData": true
  }
];
window.MYCOIFFEUR_DATA = { RUN_META, MAESTRO_FLOWS, APPIUM_TESTS, CI_WORKFLOWS, HISTORY, COMMITS };
